# Generated by Django 5.2.6 on 2025-10-30 15:07

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learn', '0002_usertopicstatistics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('friend', 'Friend'), ('mentor', 'Mentor')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('personality', models.JSONField(blank=True, default=dict, null=True)),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.learningtopic')),
            ],
            options={
                'verbose_name': 'AI Character',
                'verbose_name_plural': 'AI Characters',
            },
        ),
        migrations.CreateModel(
            name='AICharacterChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.aicharacter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Character Chat',
                'verbose_name_plural': 'AI Character Chats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.aicharacter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Character Chat',
                'verbose_name_plural': 'AI Character Chats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aicharacter',
            index=models.Index(fields=['topic'], name='characters__topic_i_58dc4a_idx'),
        ),
        migrations.AddIndex(
            model_name='aicharacter',
            index=models.Index(fields=['role'], name='characters__role_8da902_idx'),
        ),
        migrations.AddIndex(
            model_name='aicharacterchatmessages',
            index=models.Index(fields=['user', 'ai_character'], name='characters__user_id_f9e49e_idx'),
        ),
        migrations.AddIndex(
            model_name='aicharacterchatmessages',
            index=models.Index(fields=['created_at'], name='characters__created_f512af_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatmemory',
            index=models.Index(fields=['user', 'ai_character'], name='characters__user_id_e6d961_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatmemory',
            index=models.Index(fields=['created_at'], name='characters__created_10e4b5_idx'),
        ),
    ]
