# Generated by Django 5.2.6 on 2025-11-01 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicharacterchatmessages',
            options={'ordering': ['created_at'], 'verbose_name': 'AI Character Chat Message', 'verbose_name_plural': 'AI Character Chat Messages'},
        ),
        migrations.RemoveField(
            model_name='aicharacterchatmessages',
            name='response',
        ),
        migrations.RemoveField(
            model_name='aicharacterchatmessages',
            name='summary',
        ),
        migrations.AddField(
            model_name='aicharacterchatmessages',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('ai', 'AI')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aicharacterchatmessages',
            name='ai_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_chat_messages', to='characters.aicharacter'),
        ),
        migrations.AlterField(
            model_name='aicharacterchatmessages',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aicharacterchatmessages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
