# Generated by Django 5.2.6 on 2025-12-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_aicharacterchatmessages_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicharacterchatmessages',
            options={'verbose_name': 'AI Character Chat Message', 'verbose_name_plural': 'AI Character Chat Messages'},
        ),
        migrations.AlterModelOptions(
            name='aichatmemory',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Character Chat memory', 'verbose_name_plural': 'AI Character Chats Memories'},
        ),
    ]
