# Generated by Django 5.2.6 on 2025-10-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
