# Generated by Django 5.2.6 on 2025-10-03 09:03

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('label', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearningCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Learning Category',
                'verbose_name_plural': 'Learning Categories',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='LearningTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=255)),
                ('topic_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learn.learningcategory')),
            ],
            options={
                'verbose_name': 'Learning Topic',
                'verbose_name_plural': 'Learning Topics',
                'ordering': ['topic'],
                'unique_together': {('category', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='UserLearningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, max_length=50)),
                ('user_answer', models.TextField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('improved_answer', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ai_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='learn.aimodels')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='learn.learningtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Learning History',
                'verbose_name_plural': 'User Learning Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
