# Generated by Django 5.2.6 on 2026-03-10 14:56

import cloudinary.models
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModels',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('label', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LearningCategory',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Learning Category',
                'verbose_name_plural': 'Learning Categories',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='LearningTopic',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(db_index=True, max_length=255)),
                ('topic_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learn.learningcategory')),
            ],
            options={
                'verbose_name': 'Learning Topic',
                'verbose_name_plural': 'Learning Topics',
                'ordering': ['topic'],
                'unique_together': {('category', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='UserLearningHistory',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, max_length=50)),
                ('user_answer', models.TextField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('improved_answer', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ai_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='learn.aimodels')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='learn.learningtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Learning History',
                'verbose_name_plural': 'User Learning Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotes',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_starred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicNode',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('level', models.CharField(choices=[('section', 'Section'), ('concept', 'Concept')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='learn.topicnode')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='learn.learningtopic')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['topic', 'parent'], name='learn_topic_topic_i_75164a_idx')],
                'unique_together': {('topic', 'parent', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserTopicStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('total_score', models.IntegerField(default=0)),
                ('questions_asked', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statistics', to='learn.learningtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Topic Statistics',
                'verbose_name_plural': 'User Topic Statistics',
                'ordering': ['-total_score'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
