# Generated by Django 5.2.6 on 2025-10-03 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTopicStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('questions_asked', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statistics', to='learn.learningtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Topic Statistics',
                'verbose_name_plural': 'User Topic Statistics',
                'ordering': ['-total_score'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
